# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
dist: trusty
julia:
  - 0.6
  - nightly
matrix:
 allow_failures:
 - julia: nightly

addons:
  apt:
    packages:
    - xorg-dev
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
notifications:
  email: false
